CREATE TABLE AccountMaster_T1
(
	Account_ID INT IDENTITY(1,1) ,
	Bank_NAME  VARCHAR(255),
    BankAccount_ID VARCHAR(20),
	AccountType_CODE VARCHAR(10),
    Owner_NAME VARCHAR(255),
    HideAccount_INDC  CHAR(1) DEFAULT 'N',
	TransactionEventSeq_NUMB   NUMERIC (19) NOT NULL,
    Update_DTTM                DATETIME2 (7) DEFAULT SYSUTCDATETIME (),
    WorkerUpdate_ID            VARCHAR (36) NULL,
    BeginValidity_DTTM         DATETIME2 (7)  GENERATED ALWAYS AS ROW START NOT NULL,
    EndValidity_DTTM           DATETIME2 (7)  GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT BANK_I1 PRIMARY KEY CLUSTERED (Account_ID ASC),
    PERIOD FOR SYSTEM_TIME (BeginValidity_DTTM, EndValidity_DTTM)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.BankMasterHist_T1, DATA_CONSISTENCY_CHECK=OFF));