CREATE TABLE ShareMarketValueHist_T1
(
	Trade_CODE VARCHAR(15) NOT NULL,
	Trade_DATE DATE NOT NULL,
	Open_AMNT  MONEY NULL ,
	Close_AMNT  MONEY NULL,
	Low_AMNT   MONEY NULL ,
	High_AMNT   MONEY NULL,
	Current_AMNT  MONEY NULL ,
	Volume_CNT Bigint,
	AvgVol_CNT BigInt,
    WorkerUpdate_ID    VARCHAR (36) NULL,
    CONSTRAINT HSHRV_I1 PRIMARY KEY CLUSTERED (Trade_CODE ,Trade_DATE)
)
