CREATE TABLE ShareMaster_T1
(
   Trade_CODE                 VARCHAR (15) NOT NULL,
   Trade_NAME                 VARCHAR (255) NULL,
   Region_NAME                VARCHAR (50) NULL,
   Country_CODE               VARCHAR (50) NULL,
   Type_CODE                  VARCHAR (25) NULL,
   Exchange_CODE              VARCHAR (25) NULL,
   Sector_NAME                VARCHAR (100) NULL,
   Currency_CODE              VARCHAR (25) NULL,
   Industry_NAME              VARCHAR (100) NULL,
   FTEmployees_CNT            INT NULL,
   LatestQuarter_DATE         DATE NULL,
   MarketGap_NUMB             BIGINT NULL,
   PERatio_NUMB               NUMERIC (10, 5) NULL,
   BookValue_NUMB             NUMERIC (10, 5) NULL,
   DividendPerShare_AMNT      MONEY NULL,
   DividendYield_NUMB         NUMERIC (10, 5) NULL,
   Eps_NUMB                   NUMERIC (10, 5) NULL,
   Week52High_AMNT            MONEY NULL,
   Week52Low_AMNT             MONEY NULL,
   Day50MovAvg_AMNT           NUMERIC (12, 4) NULL,
   Day200MovAvg_AMNT          NUMERIC (12, 4) NULL,
   Dividend_DATE              DATE,
   ExDividend_DATE            DATE,
   BuyReco_INDC               CHAR (1) NULL DEFAULT 'N',
   BuyRecoBy_NAME             VARCHAR (50),
   BuyReco_DATE               DATE,
   SoldAt_AMNT                MONEY  NULL DEFAULT 0,
   SoldOn_DATE                DATE   NULL,
   TransactionEventSeq_NUMB   NUMERIC (19) NOT NULL,
   Update_DTTM                DATETIME2 (7) DEFAULT SYSUTCDATETIME (),
   WorkerUpdate_ID            VARCHAR (36) NULL,
   CONSTRAINT SHRM_I1 PRIMARY KEY CLUSTERED (Trade_CODE ASC)
)
