CREATE TABLE ShareTradeValue_T1
(
	Trade_CODE       VARCHAR(15) NOT NULL,
	BuyAt_AMNT       MONEY NULL ,
	SellAt_AMNT      MONEY NULL,
	Update_DTTM      DATETIME2 (7) DEFAULT SYSUTCDATETIME (),
    WorkerUpdate_ID  VARCHAR (36) NULL,
	CONSTRAINT STDV_I1 PRIMARY KEY CLUSTERED (Trade_CODE ASC)
)
